security:
    password_hashers:
        App\Entity\Client:
            algorithm: auto

    providers:
        app_client_provider:
            entity:
                class: App\Entity\Client
                property: mailCli

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_client_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                username_parameter: mailCli
                password_parameter: password
            logout:
                path: app_logout
                target: app_home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

    access_control:
        - { path: ^/compte, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }